version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v2.4.4
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            /scripts/build-image.sh web3f/substrate-telemetry .
  helmLint:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/substrate-telemetry

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/substrate-telemetry

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - buildImage:
          context: dockerhub-bot
          filters:
            tags:
              only: /.*/
      - helmLint:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage
            - helmLint
      - publishChart:
          context: github-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - integrationTests
      - publishImage:
          context: dockerhub-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - integrationTests
