image:
  repo: web3f/substrate-telemetry
  tag: v2.5.0

environment: production

endpointSubdomain: telemetry
domain: testnet.w3f.tech

frontendPort: 3000
backendPortCore: 8001
backendPortShard: 8000

exporter:
  resources:
    limits:
      memory: 400Mi
    requests:
      memory: 400Mi
  enabled: true
  port: 3000
  image:
    repo: web3f/substrate-telemetry-exporter
    tag: v2.1.0
  config:
    subscribe:
      chains:
      - Kusama
      validators: []

certificate:
  enabled: true

alertrules:
  general:
    enabled: true
  validators:
    enabled: false

whiteListSourceRange: "0.0.0.0/0"

backend:
  resources:
    limits:
      cpu: 100m
      memory: 800Mi
    requests:
      cpu: 100m
      memory: 800Mi

ingress:
  enabled: true

frontend:
  enabled: true
