{{- if .Values.exporter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "substrate-telemetry.exporterName" . }}
data:
  main.yaml: |-
{{ toYaml .Values.exporter.config | indent 4 }}
    telemetry_host: ws://{{ include "substrate-telemetry.backendAppName" . }}-core:{{ .Values.backendPortCore }}/feed
{{ end }}
