apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "substrate-telemetry.frontendAppName" . }}
data:
  env-config.js: |-
    window.process_env = {
      SUBSTRATE_TELEMETRY_URL: "wss://{{ include "substrate-telemetry.backendDomain" . }}/feed",
      SUBSTRATE_TELEMETRY_SAMPLE: "",
    }
