apiVersion: v1
kind: Service
metadata:
  name: {{ include "substrate-telemetry.backendSvcName" . }}-shard
  labels:
    app: {{ include "substrate-telemetry.backendSvcName" . }}-shard
spec:
  ports:
  - name: backend
    port: {{ .Values.backendPortShard }}
  {{- if .Values.exporter.enabled }}
  - name: metrics
    port: {{ .Values.exporter.port }}
  {{- end }}
  selector:
    app: {{ include "substrate-telemetry.backendAppName" . }}-shard
